version: '2.1'
services:
  sqlexpress:
    image: microsoft/mssql-server-windows-express
    environment:
      sa_password: "Tot@11y5ecr3t"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:  
      - "sqlexpress"         
    ports:
      - "8000:80"    
